In [1]:
def dfs(graph, start, visited):
    print(start, end=' ')
    visited[start] = True

    for neighbor in graph[start]:
        if not visited[neighbor]:
            dfs(graph, neighbor, visited)

In [2]:
# Adjacency list representation of the graph
graph = {
    1: [2, 3],
    2: [1, 4],
    3: [1, 5],
    4: [2],
    5: [3]
}

In [3]:
# Starting vertex
start_vertex = 1

In [4]:
# Visited array to keep track of visited vertices
visited = {vertex: False for vertex in graph}

In [5]:
# DFS traversal
print("DFS traversal:")
dfs(graph, start_vertex, visited)

DFS traversal:
1 2 4 3 5 

In [5]:
#definition

def dfs2(graph, start):
    stack = [(start, iter(graph[start]))]
    visited = set()

    while stack:
        vertex, neighbors_iter = stack[-1]

        try:
            neighbor = next(neighbors_iter)
            if neighbor not in visited:
                print(neighbor, end=' ')
                visited.add(neighbor)
                stack.append((neighbor, iter(graph[neighbor])))
        except StopIteration:
            stack.pop()
graph = {
    'A': ['B', 'S'],
    'B': ['A'],
    'C': ['D', 'E', 'F', 'S'],
    'D': ['C'],
    'E': ['C', 'H'],
    'F': ['C', 'G'],
    'G': ['F', 'H', 'S'],
    'H': ['E', 'G'],
    'S': ['A', 'C', 'G']
}
# Starting vertex and applying DFS with the second implementation
start_vertex = 'A'
print("DFS traversal (dfs2) starting from vertex", start_vertex)
dfs2(graph,start_vertex)

DFS traversal (dfs2) starting from vertex A
B A S C D E H G F 

In [6]:
import numpy as np

# Define the initial and final states
initial_state = np.array([[2, 8, 3],
                          [1, 6, 4],
                          [7, 0, 5]])

final_state = np.array([[1, 2, 3],
                        [8, 0, 4],
                        [7, 6, 5]])


# Define the heuristic function
def heuristic(state):
    # A simple heuristic: count the number of misplaced tiles
    return np.sum(state != final_state)


from queue import PriorityQueue

# Implement the A* algorithm
def astar(initial_state, final_state, heuristic):
    priority_queue = PriorityQueue()
    priority_queue.put((heuristic(initial_state), 0, initial_state.tolist()))
    visited = set()

    while not priority_queue.empty():
        _, cost, current_state = priority_queue.get()
        current_state = np.array(current_state)

        if np.array_equal(current_state, final_state):
            return current_state

        if tuple(current_state.flatten()) in visited:
            continue

        visited.add(tuple(current_state.flatten()))

        # Generate neighbors
        zero_position = np.argwhere(current_state == 0)[0]
        moves = [(0, 1), (1, 0), (0, -1), (-1, 0)]

        for move in moves:
            new_position = zero_position + move
            if 0 <= new_position[0] < 3 and 0 <= new_position[1] < 3:
                new_state = current_state.copy()
                new_state[zero_position[0], zero_position[1]] = current_state[new_position[0], new_position[1]]
                new_state[new_position[0], new_position[1]] = 0

                if tuple(new_state.flatten()) not in visited:
                    priority_queue.put((heuristic(new_state) + cost + 1, cost + 1, new_state.tolist()))

    return None


# Call the A* algorithm with the initial and final states
result = astar(initial_state, final_state, heuristic)

# Print the result or perform further actions as needed
if result is not None:
    print("Final State:")
    print(result)
else:
    print("A* algorithm did not find a solution.")

Final State:
[[1 2 3]
 [8 0 4]
 [7 6 5]]
